name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupérer le fichier zip et le dossier du dépôt
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Décompresser automatiquement votre fichier niswo.zip
    - name: Unzip project files
      run: |
        unzip -o niswo.zip
        echo "Contenu du répertoire après extraction :"
        ls -la

    # 3. Configurer l'environnement Java
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 4. Donner les permissions et compiler l'APK
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug

    # 5. Sauvegarder l'APK généré pour le télécharger
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: |
          **/build/outputs/apk/debug/*.apk
